config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  resources :posts do
    member do
      get "user" => "posts#find_user"
      post "publish" => "posts#publish_post"
    end
    resources :ratings, only: [:create, :destroy]
  	resources :comments
  end

  resources :followings, only: [:create, :destroy]

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user
      can :create, Post
      can :create, Comment
      can :create, Following
      can :destroy, Following
    
      can :update, Comment do |comment|
        comment.user == user
      end
      can :destroy, Comment do |comment|
        comment.user == user
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
  belongs_to :follower, :class_name => 'User'
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy

  validates :title, presence: true
  validates :details, presence: true

  scope :other_user, ->(current_user) { where.not(user_id: current_user.id, publish: false) }
end

app/models/rating.rb
class Rating < ApplicationRecord

  belongs_to :post
  belongs_to :user
  validates_inclusion_of :star, :in => 1..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followings
  has_many :followers, :through => :followings

  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_comment_of_post, only: [:edit, :update, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_path(@post), notice: "Comment Created Successfully"
    else
      redirect_to post_path(@post), notice: "Something went wrong"
    end
 	end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: "Updated Successfully"
    else
      redirect_to post_path(@post), notice: "You are not authorized to edit this comment"
    end
  end

 	def destroy
 		if @comment.destroy
	    redirect_to post_path(@post), notice: "Comment deleted Successfully"
	  else
	   	redirect_to post_path(@post), notice: "You are not authorized to delete this comment"
	  end
 	end

 private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_comment_of_post
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

  def create
    @follow = current_user.followings.build(:follower_id => params[:follower_id])
    if @follow.save
      flash[:notice] = "Following Successfully."
      redirect_to root_url
    else
      flash[:notice] = "Unable to follow."
      redirect_to root_url
    end
  end

  def destroy
    @following = Following.find_by(follower_id: params[:follower_id])
    if @following
      @following.destroy
      flash[:notice] = "Remove from following list"
      redirect_to root_url
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy, :publish_post, :find_user]

  def new
	  @post = current_user.posts.new
	end

	def create
	  @post = current_user.posts.new(post_params)
	  if @post.save
	  	redirect_to posts_path
	  else
	  	render 'new'
	  end
	end

	def edit
	end

	def update
	  if @post.update(post_params)
	    redirect_to @post
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @post.destroy
	  redirect_to posts_path
	end

	def show
	end

	def index
	  # @posts = Post.paginate(:page => params[:page], per_page: 3).where(publish: true)
    @posts = current_user.posts + Post.other_user(current_user)
    @posts = (current_user.posts.paginate(:page => params[:page]) + Post.other_user(current_user).paginate(:page => params[:page]))
	end

  def publish_post
    @post.publish = !@post.publish
    if @post.save
      redirect_to post_path(@post), notice: "Post Published Successfully!"
    else
      redirect_to post_path(@post), notice: "Something Went Wrong!"
    end
  end

  def find_user
     @user = @post.user
  end

 private

  def post_params
    params.require(:post).permit(:title, :details)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @rating = @post.ratings.build(rating_params)
    @rating.user_id = current_user.id
    if @rating.save
      redirect_to post_path(@post), notice: "Successfully Submited"
    else
      redirect_to post_path(@post), notice: "Something went Wrong"
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    rating = Rating.find(params[:id])
    if rating.destroy
      redirect_to post_path(post), notice: "Successfully Deleted"
    else
      redirect_to post_path(post), notice: "Something went Wrong"
    end
  end

  private

   def rating_params
     params.require(:rating).permit(:star)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/comments/_comment.html.erb
<br><br><p>
  <strong>Commenter:</strong>
  <%= comment.user.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if current_user.followings.map(&:follower_id).include?(@post.user.id) %>
<p>
  <%= link_to "Edit", edit_post_comment_path(comment.post, comment), class: "btn btn-primary" if can? :update, comment %>
  <%= link_to 'Destroy Comment', [comment.post, comment], class: "btn btn-danger",
               method: :delete,
               data: { confirm: 'Are you sure?' } if can? :destroy, comment %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <% if current_user.followings.map(&:follower_id).include?(@post.user.id) || current_user == @post.user %>
  <h2>Add a comment:</h2>
    <p>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>


<%= form_with(model: [@post, @comment], local: true) do |form| %>

  <p>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>


<%= link_to 'Back', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
   </p>

   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
<% if @post.present? %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :details %><br>
    <%= form.text_area :details %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/find_user.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<% unless current_user == @user %>
  <% if current_user.followings.present? && current_user.followings.map(&:follower_id).include?(@user.id) %>
    <%= link_to "Unfollow",following_path(:follower_id => @user), :method => :delete, class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Follow", followings_path(:follower_id => @user), :method => :post, class: "btn btn-primary" %>
  <% end %>
<% end %>
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<table class="table" >
  <tr>
    <th>Title</th>
    <th>Details</th>
    <th>Author Name</th>
    <th colspan="3"></th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.details %></td>
      <td><%= link_to "#{post.user.name}", user_post_path(post) %></td>
      <td><%= link_to 'Show', post_path(post), class: "btn btn-primary" %></td>

      <% if post.user == current_user && !post.publish %>
      <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-success" %></td>
      <td><%= link_to 'Destroy', post_path(post), class: "btn btn-danger",
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<%#= will_paginate @posts %><br>

<%= link_to 'New post', new_post_path, class: "btn btn-primary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.details %>
</p>

<%= link_to "Publish Post", publish_post_path(@post), class: "float-right btn btn-primary", method: :post if @post.user == current_user && !@post.publish %>

<%= render @post.comments %>
<%= render @post.ratings %>


<%= render 'comments/form' %>
<%= render 'ratings/form' %>

<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

app/views/ratings/_form.html.erb
<%= form_with(model: [ @post, @post.ratings.build ], local: true) do |form| %>
  <% unless @post.ratings.map(&:user_id).include?(current_user.id) %>
    <p>
      <%= form.number_field :star %>
    </p>
    <p>
      <%= form.submit "Submit Rating" %>
    </p>
  <% end %>
<% end %>

app/views/ratings/_rating.html.erb
<br><br>
  <ul>
    <% @post.ratings.each do |rating|  %>
      <li><%= "#{rating.user.name} give #{rating.star} rating to this post" %></li>
        <%= link_to 'Remove Rating', post_rating_path(@post, rating), class: "btn btn-danger",
                     method: :delete,
                     data: { confirm: 'Are you sure?' } %>
    <% end %>
  </ul>

<%# if current_user.followings.map(&:follower_id).include?(@post.user.id) %>

<%# end %>